### ISSUE TITLE
summing negative values

### ISSUE THREAD

**Issue by bzinszer** [TeamMCPA/Consortium-Analyses#33]
https://github.com/TeamMCPA/Consortium-Analyses/blob/8dd4b0162454028069e004eabd1c4b5aec51b416/MCP_relabel_stimuli.m#L95

Analyzing new dataset, and encountered negative values in s-matrix, which might be user-added in some pre-preprocessing routine. Event-counting needs to be updated to force logical and handle negatives (logical 1 by default, but probably should be logical 0)

Consider: `if length(new_labels) ~= sum(old_cond_onsets>0)`

And search the function for other similar behavior.

**Comment by aherbolz** [comment]
to do- add: 
if length(new_labels)==1 && sum(old_cond_onsets)==1
    % Case (3): In the occasional instance that there is only one onset, it
    % won't meet the criteria above, but we still just want to do a label
    % swap in the Conditions rather than adding a new column.
    disp('Only one onset found for this label. Replacing');
    new_mcp_file = old_mcp_struct;
    new_mcp_file.Experiment.Conditions(old_cond_index).Name = new_labels{:};
    return    
end

to line 112
