### ISSUE TITLE
bug in quick_plot_chans

### ISSUE THREAD

**Issue by aherbolz** [TeamMCPA/Consortium-Analyses#9]
https://github.com/TeamMCPA/Consortium-Analyses/blob/e90eb3b82bf88dc83843e08f10d65626866db8c0/visualization/quick_plot_chans.m#L120-L137

Received following Matlab output: "Undefined function 'showChanData'
for input arguments of type
'matlab.graphics.chart.primitive.Line'. 
Error using LiveEditorEvaluationHelperESectionEval7026304b (line 94)
Error while evaluating Line ButtonDownFcn."

**Comment by aherbolz** [comment]
bug in quick_plot_chans: seems as though the while loop makes it so that sometimes the plot is responsive and other times it is not. could be due to having more than 1 plot up at a time

**Comment by bzinszer** [comment]
I can't replicate the problem, but I suspect it might have to do with multiple elements in the same spot (like the channel lines overlapping the detector point). I added an option to prevent the lines from being drawn. Enter 0 as the second argument, and see if the problem goes away?

**Comment by aherbolz** [comment]
This works now!
